### ISSUE TITLE
On pull request merged cleanup merged branch

### ISSUE THREAD

**Issue by shouze** [inextensodigital/actions#2]
# Why

To avoid to have to do some manual cleaning.

# When

- Triggered [on pull request merged](https://github.com/jessfraz/branch-cleanup-action/blob/4c8b444e9293a9f888bcdd86366d7dba7fdce3c3/cleanup-pr-branch#L25-L26)

**Comment by kesslerdev** [comment]
with https://github.com/inextensodigital/actions/commit/3048683a6411788c57db6b45dcb1db1183b8e2f2
 see: https://github.com/inextensodigital/invoicing.app/pull/1515
